### ISSUE TITLE
the ./slam keeps throwing out error

### ISSUE THREAD

**Issue by feiran-l** [yilei0620/RGBD-Slam-Semantic-Seg-DeepLab#2]
Hi, I was first trying the code and it kept throwing errors:

> 
> Reading files 201
> find total 0 matches.
>  good matches: 0
>  Not enough inliers.
>  .
>  .
>  .
> Reading files 392
> find total 0 matches.
>  good matches: 0
>  Not enough inliers
> 
> WARNING: Logging before InitGoogleLogging() is written to STDERR
> E1114 13:04:10.285167 21636 ceresbase.h:242] Error opening the file: ./data/poses_original.txt
> F1114 13:04:10.285238 21636 slamDP.cpp:132] Check failed: ceres::examples::OutputPoses("./data/poses_original.txt", poses) Error outputting to poses_original.txt
> *** Check failure stack trace: ***
> Aborted (core dumped)

I used the default` **parameter.txt**` and the `**TUM RGBD benchmark dataset**` for test. Any ideas about this?

**Comment by yilei0620** [comment]
I tested on NYU depth v2 data set. 
I think you should change some parameters in `parameter.txt`.Perhaps `sift feature` and lower thresholds will work.

I will look at that dataset recently and try to figure out why it can't find matches.

**Comment by feiran-l** [comment]
I changed the `parameter.txt` but still error. I think maybe there are soming compiling mistakes. would you like to provide the **PCL version** and **ceres version** you used?

**Comment by yilei0620** [comment]
I'm using pcl 1.7 and ceres 1.3.

It shouldn't be the problem from pcl and ceres packages since matching features are all under opencv.

Did you preprocess rgb frames and depth frames? Correct form of rgb frames is `CV_8UC3` (which I think you don't need to process them). If the depth images are in raw form, I think you need to preprocess them. However, I still don't think depth image preprocessing will affect matching process since I just use rgb features to do matching.

I'll test it on that data set to see where it goes wrongly.

**Comment by feiran-l** [comment]
OK, waiting for your result

**Comment by YiChenCityU** [comment]
Thanks for your sharing. Have  you published paper about this? I want to read it.

**Comment by yilei0620** [comment]
@codefordead, I have not published a paper about this since I don't think it contains some innovative ideas. It is an integration of some interesting things and thank you if you are interested. You can find the exact ideas through googling `rgbd-slam` and `semantic segmentation` separately.

@SILI1994, I'll try the dataset in the weekend. I'm quite busy during weekdays. Sorry to keep you waiting.

**Comment by feiran-l** [comment]
thank you very much, i am also checking my opencv to see if something wrong

**Comment by yilei0620** [comment]
@SILI1994 Hi,

I tried well on TUM dataset. I think that I forgot to mention that you need save rgb and depth data with name like `./data/rgb_png/1.png`, `./data/rgb_png/2.png` ... (in the form of uint8) and `./data/depth_png/1.png`, `./data/depth_png/2.png` ... (int the form of uint16). The depth images' name should be the same as rgb images. The order of names represents the time sequence.

I mentioned this in the readme.

However, the results were not good based on the parameters that I tested on nyu depth v2 dataset. I think you need to tune the parameters according to different hardware settings.

**Comment by feiran-l** [comment]
Thank you again for your trying. But I have made the dataset as required. And I have extracted the 
 `keypoints detection `code and the `matching` code out to test them and it works well. So I think there is something wrong with the` link to opencv in the cmakefile`. Anyway i will try to figure this by myself. thank you!
